<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    User
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * User index view script
 * 
 * @package    User
 */
$this->headTitle('Benutzer anzeigen');
$this->pageTitle('Schön, dass Sie da sind');
?>
<p>
<?php $url = $this->url('user-admin'); ?>
<a href="<?php echo $url; ?>" class="btn">Benutzer verwalten</a>
<?php $url = $this->url('user', array('action' => 'register')); ?>
<a href="<?php echo $url; ?>" class="btn">Benutzer registrieren</a>
<a href="/" class="btn">Zurück zur Homepage</a>
</p>