<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */

$this->headTitle('Listings - Kapitel 17');
$this->pageTitle('Listings - Kapitel 17');
?>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing1701">Listing 17.1</a></td>
<td>Aufbau der Datenbank</td>
</tr>
<tr>
<td><a href="/listing/listing1702">Listing 17.2</a></td>
<td><code>DbBcryptAdapter</code> Authentifizierungsadapter</td>
</tr>
<tr>
<td><a href="/listing/listing1703">Listing 17.3</a></td>
<td>Factory für <code>DbBcryptAdapter</code></td>
</tr>
<tr>
<td><a href="/listing/listing1704">Listing 17.4</a></td>
<td>Konfiguration <code>DbBcryptAdapter</code>-Factory in <code>module.config.php</code></td>
</tr>
<tr>
<td><a href="/listing/listing1705">Listing 17.5</a></td>
<td><code>ServiceFactory</code> für <code>AuthenticationService</code></td>
</tr>
<tr>
<td><a href="/listing/listing1706">Listing 17.6</a></td>
<td>Service für die Generierung und Verarbeitung eines <code>Acl</code>-Objektes</td>
</tr>
<tr>
<td><a href="/listing/listing1707">Listing 17.7</a></td>
<td><code>ServiceFactory</code> für <code>User\Acl\Service</code></td>
</tr>
<tr>
<td><a href="/listing/listing1708">Listing 17.8</a></td>
<td>Konfiguration Factories in <code>module.config.php</code></td>
</tr>
<tr>
<td><a href="/listing/listing1709">Listing 17.9</a></td>
<td>Konfiguration der Benutzerrechte für <code>User</code>-Modul</td>
</tr>
<tr>
<td><a href="/listing/listing1710">Listing 17.10</a></td>
<td>Konfiguration der Benutzerrechte für <code>Application</code>-Modul</td>
</tr>
<tr>
<td><a href="/listing/listing1711">Listing 17.11</a></td>
<td>Konfiguration der Benutzerrechte für <code>Blog</code>-Modul</td>
</tr>
<tr>
<td><a href="/listing/listing1712">Listing 17.12</a></td>
<td>Änderungen für <code>UserService</code> Teil 1</td>
</tr>
<tr>
<td><a href="/listing/listing1713">Listing 17.13</a></td>
<td>Änderungen für <code>UserService</code> Teil 2</td>
</tr>
<tr>
<td><a href="/listing/listing1714">Listing 17.14</a></td>
<td>Konfiguration der View-Helper aus dem <code>User</code> Modul</td>
</tr>
<tr>
<td><a href="/listing/listing1715">Listing 17.15</a></td>
<td><code>UserIsAllowed</code> View-Helper zum Prüfen der Benutzerrechte</td>
</tr>
<tr>
<td><a href="/listing/listing1716">Listing 17.16</a></td>
<td><code>UserShowWidget</code> View-Helper zur Anzeige eines Widgets</td>
</tr>
<tr>
<td><a href="/listing/listing1717">Listing 17.17</a></td>
<td>Konfiguration der View-Skripte für die <code>User</code>-Widgets</td>
</tr>
<tr>
<td><a href="/listing/listing1718">Listing 17.18</a></td>
<td>View-Skript <code>login.phtml</code> für Login-Widget</td>
</tr>
<tr>
<td><a href="/listing/listing1719">Listing 17.19</a></td>
<td>View-Skript <code>logout.phtml</code> für Logout-Widget</td>
</tr>
<tr>
<td><a href="/listing/listing1720">Listing 17.20</a></td>
<td><code>UserListener</code> zum Überprüfen der Benutzerrechte</td>
</tr>
<tr>
<td><a href="/listing/listing1721">Listing 17.21</a></td>
<td><code>forbiddenAction()</code> Methode aus dem <code>UserController</code></td>
</tr>
<tr>
<td><a href="/listing/listing1722">Listing 17.22</a></td>
<td><code>UserController</code> stellt öffentlichen Bereich für <code>User</code> Modul bereit</td>
</tr>
<tr>
<td><a href="/listing/listing1723">Listing 17.23</a></td>
<td><code>index.phtml</code> zeigt Benutzer Introseite an</td>
</tr>
<tr>
<td><a href="/listing/listing1724">Listing 17.24</a></td>
<td><code>login.phtml</code> zeigt Anmeldeformular an</td>
</tr>
</tbody>
</table>
