<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 17.18 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 17.18');
$this->pageTitle('Listing 17.18');
?>
<h3>View-Skript <code>login.phtml</code> für Login-Widget</h3>
<pre>
&lt;?php
$actionUrl = $this-&gt;url('user', array('action' =&gt; 'login'));
?&gt;
&lt;div class="well"&gt;
&lt;h4 class="pull-center"&gt;Sie sind nicht angemeldet&lt;/h4&gt;
&lt;?php echo $this-&gt;showForm($this-&gt;form, $actionUrl, 'form-vertical'); ?&gt;
&lt;/div&gt;
</pre>
