<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 17.17 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 17.17');
$this->pageTitle('Listing 17.17');
?>
<h3>Konfiguration der View-Skripte für die <code>User</code>-Widgets</h3>
<pre>
&lt;?php
return array(
    [...]
    
    'view_manager' => array(
        'template_map' => array(
            'widget/logout' => realpath(__DIR__ . '/../view/user/widget/logout.phtml'),
            'widget/login'  => realpath(__DIR__ . '/../view/user/widget/login.phtml'),
        ),
        [...]
    ),
    
    [...]
);
</pre>
