<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 17.15 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 17.15');
$this->pageTitle('Listing 17.15');
?>
<h3><code>UserIsAllowed</code> View-Helper zum Prüfen der Benutzerrechte</h3>
<pre>
&lt;?php
namespace User\View\Helper;

use Zend\View\Helper\AbstractHelper;
use User\Acl\Service as AclService;

class UserIsAllowed extends AbstractHelper
{
    protected $acl;

    public function __construct(AclService $acl)
    {
        $this->setAcl($acl);
    }

    public function setAcl(AclService $acl = null)
    {
        $this->acl = $acl;
        return $this;
    }
    
    public function getAcl()
    {
        return $this->acl;
    }
    
    public function __invoke($resource, $privilege = 'index')
    {
        return $this->getAcl()->isAllowed($resource, $privilege);
    }
}
</pre>
