<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 17.24 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 17.24');
$this->pageTitle('Listing 17.24');
?>
<h3><code>login.phtml</code> zeigt Anmeldeformular an</h3>
<pre>
&lt;?php
$this-&gt;headTitle('Anmelden');
$this-&gt;pageTitle('Als Benutzer anmelden');

$actionUrl = $this-&gt;url('user/action', array('action' =&gt; 'login'));
echo $this-&gt;showForm($this-&gt;form, $actionUrl, 'form-horizontal');
?&gt;
&lt;hr /&gt;
&lt;h3&gt;Sie sind noch nicht angemeldet?&lt;/h3&gt;
&lt;?php $url = $this-&gt;url('user/action', array('action' =&gt; 'register'))?&gt;
&lt;a href="&lt;?php echo $url; ?&gt;" class="btn"&gt;Jetzt registrieren&lt;/a&gt;
</pre>
