<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 17.12 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 17.12');
$this->pageTitle('Listing 17.12');
?>
<h3>Änderungen für <code>UserService</code> Teil 1</h3>
<pre>
&lt;?php
namespace User\Service;

use Zend\Authentication\AuthenticationService;
use Zend\Authentication\Storage\Session;
use Zend\Session\Container;
[...]

class UserService implements 
    EventManagerAwareInterface, 
    UserServiceInterface
{
    [...]
    
    protected $authentication = null;
    
    [...]
    
    public function __construct(UserTableInterface $table, AuthenticationService $authentication)
    {
        $this->setTable($table);
        $this->setAuthentication($authentication);
    }
    
    [...]
    
    public function getAuthentication()
    {
        return $this->authentication;
    }
    
    public function setAuthentication(AuthenticationService $authentication)
    {
        $this->authentication = $authentication;
        return $this;
    }

    [...]
    
    public function save(array $data, $id = null)
    {
        [...]
        
            $bcrypt = $this->getAuthentication()->getAdapter()->getBcrypt();
            
        [...]
    }
    
    [...]
}
</pre>
