<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 17.3 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 17.3');
$this->pageTitle('Listing 17.3');
?>
<h3>Factory für <code>DbBcryptAdapter</code></h3>
<pre>
&lt;?php
namespace User\Authentication;

use Zend\Crypt\Password\Bcrypt;
use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class DbBcryptAdapterFactory implements FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $table   = $serviceLocator->get('User\Table\User');
        $bcrypt  = new Bcrypt(array('cost' => '12'));
        $adapter = new DbBcryptAdapter($table, $bcrypt);
        return $adapter;
    }
}
</pre>
