<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 17.7 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 17.7');
$this->pageTitle('Listing 17.7');
?>
<h3><code>ServiceFactory</code> für <code>User\Acl\Service</code></h3>
<pre>
&lt;?php
namespace User\Acl;

use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class ServiceFactory implements FactoryInterface
{
    public function createService(ServiceLocatorInterface $serviceLocator)
    {
        $config = $serviceLocator->get('Config');
        $auth   = $serviceLocator->get('User\Auth\Service');
        $role   = $auth->hasIdentity() 
                ? $auth->getIdentity()->getGroup() 
                : 'guest';
        $acl    = new Service($role, $config['acl']);
        return $acl;
    }
}</pre>
