<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 17.1 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 17.1');
$this->pageTitle('Listing 17.1');
?>
<h3>Aufbau der Datenbank</h3>
<pre>
CREATE TABLE users (
    id integer primary key, 
    role varchar(8), 
    email varchar(128), 
    pass varchar(60), 
    firstname varchar(32), 
    lastname varchar(32)
);
</pre>
