<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 17.14 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 17.14');
$this->pageTitle('Listing 17.14');
?>
<h3>Konfiguration der View-Helper aus dem <code>User</code> Modul</h3>
<pre>
&lt;?php
return array(
    [...]
    
    'view_helpers' => array(
        'factories'=> array(
            'UserShowWidget' => 'User\View\Helper\UserShowWidgetFactory',
            'UserIsAllowed'  => 'User\View\Helper\UserIsAllowedFactory',
        ),
    ),
    
    [...]
);
</pre>
