<?php 
/**
 * ZF2 Buch Kapitel 17
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 17.11 view script
 * 
 * @package    Application
 */

$this->headTitle('Listing 17.11');
$this->pageTitle('Listing 17.11');
?>
<h3>Konfiguration der Benutzerrechte für <code>Blog</code>-Modul</h3>
<pre>
&lt;?php
return array(
    [...]
    
    'acl' => array(
        'guest'   => array(
            'blog' => array('allow' => null),
        ),
        'staff'   => array(
            'blog-admin' => array('allow' => null),
        ),
    ),
);
</pre>
